markdown: rdiscount
permalink: /posts/:title
rdiscount:
  extensions: [smart]

gems:
  - jekyll-sitemap

name: Sam Sen 
url: http://sss.com
description: A fantastic blog that is fantastic.
twitter: sdotsen 
